"""agent platform init

Revision ID: da21c8e2e67c
Revises:
Create Date: 2026-06-25 11:12:46.651974

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "da21c8e2e67c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="Agent 主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "owner_id",
            sa.String(length=64),
            nullable=False,
            comment="Agent 所属用户 ID。",
        ),
        sa.Column("name", sa.String(length=128), nullable=False, comment="Agent 展示名称。"),
        sa.Column("description", sa.String(length=512), nullable=False, comment="Agent 描述。"),
        sa.Column(
            "system_prompt",
            sa.String(length=4096),
            nullable=False,
            comment="Agent 系统提示词。",
        ),
        sa.Column(
            "model",
            sa.String(length=128),
            nullable=False,
            comment="Agent 使用的模型标识，例如 openai/gpt-4o。",
        ),
        sa.Column("tool_ids", sa.JSON(), nullable=False, comment="Agent 启用的工具 ID 列表。"),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            comment="Agent 状态：idle、running、error、offline。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间，UTC，数据库端默认值。",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最近一次更新时间，UTC，数据库端自动维护。",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Agent 表，存储用户创建的 Agent 配置信息。",
    )
    op.create_index(op.f("ix_agent_owner_id"), "agent", ["owner_id"], unique=False)
    op.create_table(
        "tool",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="工具主键 ID，全局唯一标识。",
        ),
        sa.Column("name", sa.String(length=128), nullable=False, comment="工具展示名称。"),
        sa.Column("description", sa.Text(), nullable=False, comment="工具描述。"),
        sa.Column(
            "handler_path",
            sa.String(length=256),
            nullable=False,
            comment="工具处理器导入路径，例如 engines.skills.tools.web_search。",
        ),
        sa.Column("schema", sa.JSON(), nullable=False, comment="工具参数 JSON Schema。"),
        sa.PrimaryKeyConstraint("id"),
        comment="工具表，存储平台预置工具的元数据。",
    )
    op.create_table(
        "user_profile",
        sa.Column(
            "id",
            sa.Integer(),
            autoincrement=True,
            nullable=False,
            comment="用户档案主键 ID，自增。",
        ),
        sa.Column(
            "username",
            sa.String(length=64),
            nullable=False,
            comment="登录用户名，全局唯一，长度 1~64。",
        ),
        sa.Column(
            "display_name",
            sa.String(length=128),
            nullable=True,
            comment="用户展示名，允许为空。",
        ),
        sa.Column("birth_date", sa.Date(), nullable=True, comment="用户出生日期，可为空。"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间，UTC，数据库端默认值。",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最近一次更新时间，UTC，数据库端自动维护。",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
        comment="用户档案表，存储系统用户的基础身份信息与展示字段。",
    )
    op.create_table(
        "workflow",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="工作流主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "owner_id",
            sa.String(length=64),
            nullable=False,
            comment="工作流所属用户 ID。",
        ),
        sa.Column("name", sa.String(length=256), nullable=False, comment="工作流名称。"),
        sa.Column("description", sa.Text(), nullable=False, comment="工作流描述。"),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            comment="工作流状态：draft、running、completed、error。",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间，UTC，数据库端默认值。",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最近一次更新时间，UTC，数据库端自动维护。",
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="工作流表，存储用户编排的工作流元数据。",
    )
    op.create_index(op.f("ix_workflow_owner_id"), "workflow", ["owner_id"], unique=False)
    op.create_table(
        "chat_session",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="会话主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "owner_id",
            sa.String(length=64),
            nullable=False,
            comment="会话所属用户 ID。",
        ),
        sa.Column(
            "agent_id",
            sa.String(length=64),
            nullable=False,
            comment="会话关联的 Agent ID。",
        ),
        sa.Column("title", sa.String(length=256), nullable=False, comment="会话标题。"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录创建时间，UTC，数据库端默认值。",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="记录最近一次更新时间，UTC，数据库端自动维护。",
        ),
        sa.ForeignKeyConstraint(
            ["agent_id"],
            ["agent.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="聊天会话表，存储用户与 Agent 的会话元数据。",
    )
    op.create_index(op.f("ix_chat_session_owner_id"), "chat_session", ["owner_id"], unique=False)
    op.create_table(
        "workflow_edge",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="边主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "workflow_id",
            sa.String(length=64),
            nullable=False,
            comment="边所属工作流 ID。",
        ),
        sa.Column(
            "source_node_id",
            sa.String(length=64),
            nullable=False,
            comment="边起始节点 ID。",
        ),
        sa.Column(
            "target_node_id",
            sa.String(length=64),
            nullable=False,
            comment="边目标节点 ID。",
        ),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="工作流边表，存储工作流节点之间的连接关系。",
    )
    op.create_index(
        op.f("ix_workflow_edge_workflow_id"),
        "workflow_edge",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "workflow_node",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="节点主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "workflow_id",
            sa.String(length=64),
            nullable=False,
            comment="节点所属工作流 ID。",
        ),
        sa.Column(
            "node_type",
            sa.String(length=64),
            nullable=False,
            comment="节点类型：start、end、agent、tool、condition。",
        ),
        sa.Column("label", sa.String(length=256), nullable=False, comment="节点展示标签。"),
        sa.Column(
            "config",
            sa.JSON(),
            nullable=False,
            comment="节点配置，例如 agent_id、tool_id、条件表达式。",
        ),
        sa.Column("position_x", sa.Float(), nullable=False, comment="节点在画布上的 X 坐标。"),
        sa.Column("position_y", sa.Float(), nullable=False, comment="节点在画布上的 Y 坐标。"),
        sa.ForeignKeyConstraint(
            ["workflow_id"],
            ["workflow.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="工作流节点表，存储工作流画布中的节点。",
    )
    op.create_index(
        op.f("ix_workflow_node_workflow_id"),
        "workflow_node",
        ["workflow_id"],
        unique=False,
    )
    op.create_table(
        "chat_message",
        sa.Column(
            "id",
            sa.String(length=64),
            nullable=False,
            comment="消息主键 ID，业务生成的唯一标识。",
        ),
        sa.Column(
            "session_id",
            sa.String(length=64),
            nullable=False,
            comment="消息所属会话 ID。",
        ),
        sa.Column(
            "role",
            sa.String(length=32),
            nullable=False,
            comment="消息角色：user、assistant、system。",
        ),
        sa.Column("content", sa.Text(), nullable=False, comment="消息文本内容。"),
        sa.Column("tool_calls", sa.JSON(), nullable=False, comment="消息附带的工具调用记录。"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="消息创建时间，UTC。",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["chat_session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="聊天消息表，存储会话中的单条消息。",
    )
    op.create_index(
        op.f("ix_chat_message_session_id"), "chat_message", ["session_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_message_session_id"), table_name="chat_message")
    op.drop_table("chat_message")
    op.drop_index(op.f("ix_workflow_node_workflow_id"), table_name="workflow_node")
    op.drop_table("workflow_node")
    op.drop_index(op.f("ix_workflow_edge_workflow_id"), table_name="workflow_edge")
    op.drop_table("workflow_edge")
    op.drop_index(op.f("ix_chat_session_owner_id"), table_name="chat_session")
    op.drop_table("chat_session")
    op.drop_index(op.f("ix_workflow_owner_id"), table_name="workflow")
    op.drop_table("workflow")
    op.drop_table("user_profile")
    op.drop_table("tool")
    op.drop_index(op.f("ix_agent_owner_id"), table_name="agent")
    op.drop_table("agent")
    # ### end Alembic commands ###
